config/routes.rb
Rails.application.routes.draw do

  #projects 경로
  resources :projects, :except => [:show]
  get 'projects/show/:id' => 'projects#show', as: 'show_project'
  post 'projects/invite/:id' =>'projects#invite', as: 'invite_project'
  post 'projects/exit/:id' => 'projects#exit'
  get 'projects/join/:project_id&:key&:user_id' => 'projects#join', as: 'join_project' 
  get 'projects/myproject'
  post 'projects/create'
  
  #posts 경로
  resources :posts do
    post "/like", to: "likes#like_toggle"

    #댓글기능 라우팅
    #post에 속한 라우팅 기능으므로 여기에 적어준다
    resources :comments, only: [:create, :destroy]
  end

  
  
  #루트 경로
  root :to => "home#index"
  get 'home/profile', to: 'home#profile', :as => :profile

  #devise 경로
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'},
    path: 'users',
    path_name: {sign_in: 'login', sign_out: 'logout'}




  #register 경로
  get 'register/info', to: 'register#info', as: 'register_info'

  match '/profile/:id/finish_signup' => 'register#info', via: [:get, :patch], :as => :finish_signup

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  
  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { :scope => :provider }

  def self.find_for_oauth(auth)
    identity = find_by(uid: auth.uid, provider: auth.provider)
    identity = create(uid: auth.uid, provider: auth.provider) if identity.nil?
    identity
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/post.rb
class Post < ApplicationRecord
	resourcify
	include Authority::Abilities
	
	belongs_to :user

	has_many :likes
	has_many :comments
	# user.rb를 참조하자
	has_many :liked_users, through: :likes, source: :user

	mount_uploader :image, PostImageUploader
end

app/models/project.rb
class Project < ApplicationRecord
  
  belongs_to :user
  has_many :participants
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord

  rolify
  include Authority::UserAbilities
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable


  has_many :posts
  has_many :likes
  has_many :comments
  
  # 어떤것을 통해 like 값을 가져오는지 명시해줘야한다 through: :likes
  # 그게 source: ...
  has_many :liked_posts, through: :likes, source: :post

  mount_uploader :avatar, AvatarUploader
  has_many :participants
  has_many :projects
  # 좋아요를 얼마나 클릭하였는지 확인
  # present?는 안에 값이 있으면 true 없으면 false를 반환한다
  def is_like?(post)
    Like.find_by(user_id: self.id,
      post_id: post.id).present?
  end


  after_create :set_default_role, if: Proc.new { User.count > 1 }

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  validates_presence_of :name
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)
    
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user 
    
    if user.nil?

      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registratio
      #없는 유저라면 새로 생성  
      if user.nil?

        user = User.new(
          name: auth.info.name || auth.extra.nickname ||  auth.uid,
          # email: email ? email : "#{auth.info.email}",
          email: auth.info.email,
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
        end
      end

    if identity.user != user
      identity.user = user
      identity.save!
    end

    user

  end
  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
  
  
  private

  def set_default_role
    add_role :user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def like_toggle
    like = Like.find_by(user_id: current_user.id,
      post_id: params[:post_id])

    if like.nil?
      Like.create(user_id: current_user.id,
        post_id: params[:post_id])
    else
      like.destroy
    end
    # rails 4의 rediret_to :back를 개선한 rails 5 의 redirect_back
    redirect_back(fallback_location: posts_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  ##devise gem 문서참조 로그인이 아닐시 해당 페이지 참조 불가 index는 제외하라
  before_action :authenticate_user!, execept: [:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize_action_for @post
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to '/posts', notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    authorize_action_for @post
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(user_id: @post.user_id, content: params[:post][:content], image: params[:post][:image])
        # 내가 수정한 내용
        logger.debug format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        logger.debug format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize_action_for @post
    @post = Post.find(params[:id])

    @post.destroy
    respond_to do |format|
      format.html { redirect_to '/posts', notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end


  def icon(shape)
    "<span class='glyphicon glyphicon-#{shape}'></span>".html_safe
  end

  def user_roles(user)
  user.roles.map(&:name).join(',').titleize
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="container">
    <div class="container-1">
        <div class="nav-hc">
            <div class="navbar-collapse collapse nav-inner-hc">
                <h1>HANCO</h1>
                <ul class="nav navbar-nav nav-inner-hc-ul-1">
                    <li class="active"><%=link_to '첫 화면', "/" %></li>
                    <li><%=link_to '소 개', "#introduce" %></li>
                    <li><%=link_to '문 의', "#" %></li>
                    <li><%=link_to '게시판', '/posts' %></li>
                </ul>

                <ul class="nav navbar-nav navbar-right nav-inner-hc-ul-2">
                    <% if user_signed_in? %>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle name-color-hc" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu size-hc">    
                                <li><%= link_to "내 프로필", profile_path %></li>
                                <li class="project-a-color"><%= link_to "프로젝트", "/projects" %></li>
                                <li><%= link_to "정보수정", edit_user_registration_path %></li>
                                <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
                            </ul>
                        </li>
                    <% else %>
                        <li class="signup-btn-color-hc-1"><%= link_to "Log In", new_user_session_path %></li>
                        <li class="signup-btn-color-hc-1"><%= link_to "Sign Up", new_user_registration_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-2">
        <div class="section">
            <div class="section-inner" id="introduce">
                <div class="section-inner-vertical-grid">
                    <div class="index-section-horizon-1">
                        <%= image_tag('monitor01.jpg') %>
                    </div>
                    <div class="index-section-horizon-2">
                        <div class="index-section-content">
                            <span>자유로운 <p style="color: #AC58FA; display: inline;">Plannig</p>과</span><br>
                            <span>달성률 확인!!</span><br><br><br><br>
                            <p style="font-family: 'Jua', sans-serif; font-size: 20px;">그 놀라운 경험을 HANCO와 함께해 보세요!</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section-inner-2">
                <div class="section-inner-2-horizon-grid">
                    <div class="section-inner-2-vertical01">
                        <%= image_tag('monitor02.png') %>
                    </div>
                    <div class="section-inner-2-vertical02">
                        <div class="section-inner-2-content-grid">
                            <span class="section-inner-2-content01">개인 프로젝트와 팀 프로젝트까지</span><br>
                            <div section-space-co></div>
                            <span class="section-inner-2-content02">
                                <p>HANCO</p>의 편리함을 느껴보세요
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="footer-inner">
            <h3>HANCO</h3>
            <p>Copyright : HandlingCode(HANCO)_박준영 and 김홍빈</p>
            <a href="https://github.com/JSPlike">깃허브 링크가즈아</a>
        </div>
    </div>

</div>
<script>
    $(window).scroll(function() {
    if($(this).scrollTop() < 70)
        $('.nav-hc').css('background-color', 'transparent'),
        $('.nav-hc h1').css('color', '#424242'),
        $('.nav-hc').css('opacity', '1'),
        $('.nav-inner-hc-ul-1 a').css('color', '#0489B1'),
        
        $(".name-color-hc").css('color', '#6E6E6E'),

        $(".name-color-hc").hover(function() {
            $(this).css("color", "#0B0B61");
            }, function(){
            $(this).css("color", "#6E6E6E"); 
        }),

        $(".nav-inner-hc-ul-1 a").hover(function() {
            $(this).css("color", "#A4A4A4");
            }, function(){
            $(this).css("color", "#0489B1"); 
        });

    else
        $('.nav-hc').css('background-color', '#585858'),
        $('.nav-hc h1').css('color', '#ffffff'),
        $('.nav-hc').css('opacity', '.95'),
        $('.nav-inner-hc-ul-1 a').css('color', '#A9D0F5'),

        $(".name-color-hc").css('color', '#E6E6E6'),

        $(".name-color-hc").hover(function() {
            $(this).css("color", "#0B2161");
            }, function(){
            $(this).css("color", "#E6E6E6"); 
        }),

        $(".nav-inner-hc-ul-1 a").hover(function() {
            $(this).css("color", "#A4A4A4");
            }, function(){
            $(this).css("color", "#A9D0F5"); 
        }),

        $(".signup-btn-color-hc-1 a").hover(function() {
            $(this).css("color", "#ffffff");
            }, function(){
            $(this).css("color", "#81BEF7");
        });

    });
</script>

app/views/home/profile.html.erb
<div style="width: 100%; text-align: center;">
	<div style="width: 20%; margin-left: 40%; margin-right: 40%;">
		<div class="card" style="margin-top: 50px; padding: 30px; border: 1px solid black; border-radius: 5px;">
				<div class="card-image">
					<% unless current_user.avatar.url.nil? %>
						<img src="<%= current_user.avatar.url %>"  style="width: 10em; height: auto;">
					<%else%>
						<img src="<%=asset_path 'basic_img.png' %>"  style="width: 10em; height: auto;">
					<% end %>
				</div>
		

			<div class="card-body">
			  <h5 class="card-title">
			  	<%= label_tag "이름" %>
					<%= current_user.name %>
				</h5>
			  <p class="card-text">저는 박준영 입니다.</p>
			</div>

			<ul class="list-group list-group-flush">
				<li class="list-group-item">
			  	<%=link_to '내 프로젝트', projects_myproject_path %>
			  </li>
			  <li class="list-group-item">
			  	<%=link_to '게시판', posts_path %>
			  </li>
			  <li class="list-group-item">
			  	<%= link_to "Roles : " + user_roles(current_user), '#' %>
			  </li>
			</ul>

			<div class="card-body">
			  <a href="/" class="card-link" style="padding-right: 20px;">뒤로 가기</a> |
			  <a href="#" class="card-link" style="padding-left: 20px;">정보 수정</a>
			</div>

		</div>
	</div>
</div>