config/routes.rb
Rails.application.routes.draw do

  #projects 경로
  resources :projects, :except => [:show]
  get 'projects/show/:id' => 'projects#show', as: 'show_project'
  post 'projects/invite/:id' =>'projects#invite', as: 'invite_project'
  post 'projects/exit/:id' => 'projects#exit'
  get 'projects/join/:project_id&:key&:user_id' => 'projects#join', as: 'join_project' 
  get 'projects/myproject'
  post 'projects/create'
  
  #posts 경로
  resources :posts do
    post "/like", to: "likes#like_toggle"

    #댓글기능 라우팅
    #post에 속한 라우팅 기능으므로 여기에 적어준다
    resources :comments, only: [:create, :destroy]
  end

  
  
  #루트 경로
  root :to => "home#index"
  get 'home/profile', to: 'home#profile', :as => :profile

  #devise 경로
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'},
    path: 'users',
    path_name: {sign_in: 'login', sign_out: 'logout'}




  #register 경로
  get 'register/info', to: 'register#info', as: 'register_info'

  match '/profile/:id/finish_signup' => 'register#info', via: [:get, :patch], :as => :finish_signup

end

app/models/project.rb
class Project < ApplicationRecord
  
  belongs_to :user
  has_many :participants
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
  end
  def show
    project_find
  end

  def myproject
    temp = Project.last #임의 값
    @participants = Participant.where('user_id = ?', current_user.id)
    # 아직 용도를 모르겠음.
    # @projects = current_user.projects
  end
  
  def invite # 함께할 파트너 초대 (파라미터 상대메일주소, 게시글번호 필요)
    invite_user = User.where('email = ?',params[:email])[0]
    invite_key = ""
    rd = Random.new

    if !invite_user # 없는 유저라면 메시지 추가필요
      message_herf('회원가입이 필요합니다.', '/') and return
    end



    # 현재 지메일로 가입한 유저는 찾을 수 없음
    invite_user.participants.each do |p|
      if p.project_id == params[:id].to_i
        message_herf('이미 등록된 유저입니다.', '/') and return
      end
    end
    


    # 20개의 임의의 인증키를 만듬
    while invite_key.length != 20
      temp = rd.rand(48..122)
      if (temp >= 48 && temp <=57) || (temp >=65 && temp<=90) || (temp>=97 && temp <=122)
        invite_key+= temp.chr
      else
        next
      end
    end
    
    # 기존에 초대명단이 있으면 가장 마지막 메일이 유효하다. 메시지 필요
    invites = Invite.where('user_id = ? AND project_id = ?', invite_user.id, params[:id].to_i)
    invites.each do |i|
      i.destroy
    end

    Invite.create(
      temp_key: invite_key,
      user_id: invite_user.id,
      
      project_id: params[:id].to_i
    )

    WebmailMailer.invite_email_send(current_user.email,invite_user.email, Invite.last).deliver_now
    # 메일보내고 redirect
    message_herf('초대완료', show_project_url(params[:id])) and return

  end

  def join # 메일로 초대메일을 받았을때
    invite_data = Invite.where('user_id = ? AND project_id = ? AND temp_key = ?', params[:user_id].to_i, params[:project_id].to_i, params[:key])[0]
    if invite_data
      Participant.create(
        project_id: params[:project_id].to_i,
        user_id: current_user.id     
      )
      invite_data.destroy 
    else
      message_herf('잘못된 접근입니다.', '/') and return
    end
    message_herf('참여완료', show_project_url(params[:project_id])) and return
  end

  def exit # 글쓴이가 아닌 사람이 게시글을 나갈시
    participant = Participant.where('project_id = ? AND user_id = ?', parasm[:id].to_i, current_user.id)
    participant.destroy


    redirect_to '/'
  end

  def destroy # 프로젝트 만든사람이 글을 삭제
    project_find
    # 참여자 모두 삭제
    @project.participants.each do |p|
      p.destroy
    end
    @project.destroy
  end

  def edit
    project_find
  end

  def create
    project = Project.create(project_params)
    project.user_id = current_user.id
    project.save

    # 게시글을 만들었으면 참여자 정보를 갱신한다.
    Participant.create(
      user_id: current_user.id,
      project_id: project.id
    )
    redirect_to show_project_url(project.id)
  end
  
  private

    def project_params
      params.permit(:title, :project_kind, :desc)
    end
    def project_find # 해당 프로젝트 게시글을 찾아옴.
      @project = Project.find(params[:id].to_i)
    end
    def message_herf(message, link)
      render html: "<script>alert('#{message}'); location.href='#{link}';</script>".html_safe
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<%# 동적폼 생성을 위한 폼태그 %>

<div class="container-fluid" style="height: 100%;">
  <div class="vertical-grid-hc">
    <div class="horizon-grid-hc">
      <%=form_tag projects_create_path, :name => "resultHiddenForm" do%>
      <%end%>
      <button id="btn-1" class="individual-project">ME</button>
      <button id="btn-2" class="team-project">WE</button>


      <!-- The Modal -->
      <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
          <span class="close">&times;</span>
          <div>                                                           
            <label>Name</label>
            <br>
            <input type="text" class="form-control" id="title">
            <br>
            <label>Description</label>
            <br>
            <textarea  class="form-control" id="description"></textarea><br>
            <input id="newProject" class="btn btn-primary" type="button" value="프로젝트 생성하기" onclick="">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div style="text-align: center;">
    <a href='/projects/myproject'><button class="btn btn-success">내 프로젝트 페이지</button></a>
  </div>
</div>
<script>
  // Get the modal
  var projectkind = 0;

  var modal = document.getElementById('myModal');

  // Get the button that opens the modal
  var btn = document.getElementById("btn-1");
  var btn2 = document.getElementById("btn-2");

  // Get the <span> element that closes the modal
  var span = document.getElementsByClassName("close")[0];                                          

  // When the user clicks on the button, open the modal 
  btn.onclick = function() {
      modal.style.display = "block";
      projectkind = 1;
  }
  btn2.onclick = function(){
      modal.style.display = "block";
      projectkind = 2;
  }
  // When the user clicks on <span> (x), close the modal
  span.onclick = function() {
      modal.style.display = "none";
  }
  newProject.onclick = function(){
      //목적지는 create title과 project_kind 보내야함

    var title = document.getElementById("title").value;
    var desc = document.getElementById("description").value;
    var form = document.resultHiddenForm;
    var hiddenField = document.createElement("input");

    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", "title");
    hiddenField.setAttribute("value", title);
    form.appendChild(hiddenField);

    hiddenField = document.createElement("input");
    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", "desc");
    hiddenField.setAttribute("value", desc);
    form.appendChild(hiddenField);

    hiddenField = document.createElement("input");
    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", "project_kind");
    hiddenField.setAttribute("value", projectkind);
    form.appendChild(hiddenField);


    form.submit();

  }
  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function(event) {
      if (event.target == modal) {
          modal.style.display = "none";
      }
  }

</script>

app/views/projects/myproject.html.erb
<nav class="navbar navbar-inverse sidebar" role="navigation">
  <div class="nav-side-menu container-fluid">
    <div class="nav-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
      </button>
        <div class="brand">프로젝트 현황</div>
    </div>

    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <div class="menu-list">        
        <ul id="menu-content" class="menu-content collapse out">
            <li class="active">
              <a href="#">
              <i class="fa fa-dashboard fa-lg"></i><span style="font-weight: bold;"> 성취도 보기</span>
              </a>
            </li>

            <li  data-toggle="collapse" data-target="#products" class="collapsed">
              <a href="#"><i class="fa fa-gift fa-lg"></i> <span> UI Elements</span> <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="products">
                <li class="active"><a href="#">CSS3 Animation</a></li>
                <li><a href="#">General</a></li>
                <li><a href="#">Buttons</a></li>
                <li><a href="#">Tabs & Accordions</a></li>
                <li><a href="#">Typography</a></li>
                <li><a href="#">FontAwesome</a></li>
                <li><a href="#">Slider</a></li>
                <li><a href="#">Panels</a></li>
                <li><a href="#">Widgets</a></li>
                <li><a href="#">Bootstrap Model</a></li>
            </ul>


            <li data-toggle="collapse" data-target="#service" class="collapsed">
              <a href="#"><i class="fa fa-globe fa-lg"></i> Services <span class="arrow"></span></a>
            </li>  
            <ul class="sub-menu collapse" id="service">
              <li>New Service 1</li>
              <li>New Service 2</li>
              <li>New Service 3</li>
            </ul>


            <li data-toggle="collapse" data-target="#new" class="collapsed">
              <a href="#"><i class="fa fa-car fa-lg"></i> New <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="new">
              <li>New New 1</li>
              <li>New New 2</li>
              <li>New New 3</li>
            </ul>


             <li>
              <a href="#">
              <i class="fa fa-user fa-lg"></i> Profile
              </a>
              </li>

             <li>
              <a href="#">
              <i class="fa fa-users fa-lg"></i> Users
              </a>
            </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<div class="container-fluid main">
  <div style="padding-top: 5%; width: 100%; margin-left: 20px;">
    <h4 class="project-list-title-hc">내 프로젝트 리스트</h4>
    <hr style="width: 98%; float: left;">
    
    <%@participants.each do |p|%>
    <%temp = Project.find(p.project_id)%>
      <div class="card" style="display: inline-block;margin: 10px;width: 19em; height: auto;background-color: white; border-radius: 5px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
        <div class="card-body poject-list-hc" style="padding: 8px;">
          <div class="list-header-target js-edinting-target is-hidden"></div>
          <h4 style="display: none;"><%=link_to temp.title, show_project_path(temp.id)%></h4>
          <textarea class="mod-list-name" aria-label="temp.title" name="formname" maxlength="512" spellcheck="false" style="overflow: hidden; word-wrap: break-word; resize: horizontal;height: 26px; cursor: pointer;"><%=temp.title%></textarea>
          <h6 class="card-subtitle mb-2 text-muted">subtitle</h6>
          <p class="card-text"><%=temp.desc%></p>
          <%= link_to show_project_path(temp.id) do %>
            <button class="btn btn-success">프로젝트 입장</button>
          <%end%>
        </div>
      </div>
    <%end%>

    <%=link_to projects_path do %>
      <div class="card" style="display: inline-block;margin: 10px;width: 18em; height: auto;background-color: white; border-radius: 5px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
        <div class="card-body poject-list-hc" style="padding: 8px;">
          <span class="glyphicon glyphicon-plus"></span>
          <span style="font-weight: bold;margin-left: 10px;">새로운 프로젝트 생성</span>
        </div>
      </div>
    <%end%>   
  </div>
</div>




<style type="text/css">

/* textarea section 이름 클릭해서 javascript에서 엔터키를 인증하여
* submit을 거치지 않고 바로 저장하는 css code
*/
/*textarea*/

  textarea.mod-list-name {
    background: transparent;
    border: 1px solid transparent;
    border-radius: 3px;
    box-shadow: none;
    font-weight: bold;
    margin: -4px 0;
    height: 20px;
    min-height: 20px;
    padding: 4px 7px;
    resize: none;
    max-height: 256px;
  }

  .list-header-target.is-hidden {
    display: none;
  }
  .list-header-target {
    cursor: pointer;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
  }
/*/textarea*/


/* side menu bar css start */

  .nav-side-menu {
    overflow: auto;
    font-family: verdana;
    font-size: 12px;
    font-weight: 200;
    background-color: #2e353d;
    position: fixed;
    right: 0;
    top: 42px;
    width: 250px;
    height: auto;
    color: #e1ffff;
  }

  body,html{
    height: 100%;
    margin: 0px;
    padding: 0px;
  }

  /* remove outer padding */
  .main .row{
    padding: 0px;
    margin: 0px;
  }

  /*Remove rounded coners*/

  nav.sidebar.navbar {
    border-radius: 0px;
  }

  nav.sidebar, .main{
    -webkit-transition: margin 200ms ease-out;
    -moz-transition: margin 200ms ease-out;
    -o-transition: margin 200ms ease-out;
    transition: margin 200ms ease-out;
  }

  /* Add gap to nav and right windows.*/
  .main{
    padding: 10px 10px 0 10px;
  }






  .nav-side-menu .brand {
  background-color: #23282e;
  line-height: 50px;
  display: block;
  text-align: center;
  font-size: 14px;
  font-family: 'Fredoka One', cursive;
  font-weight: bold;
  }
  .nav-side-menu .toggle-btn {
    display: none;
  }
  .nav-side-menu ul,
  .nav-side-menu li {
    list-style: none;
    padding: 0px;
    margin: 0px;
    line-height: 35px;
    cursor: pointer;
  }
  .nav-side-menu ul :not(collapsed) .arrow:before,
  .nav-side-menu li :not(collapsed) .arrow:before {
    font-family: FontAwesome;
    content: "\f078";
    display: inline-block;
    padding-left: 10px;
    padding-right: 20px;
    vertical-align: middle;
    float: right;
  }
  .nav-side-menu ul .active,
  .nav-side-menu li .active {
    border-left: 3px solid #d19b3d;
    background-color: #4f5b69;
  }
  .nav-side-menu ul .sub-menu li.active,
  .nav-side-menu li .sub-menu li.active {
    color: #d19b3d;
  }
  .nav-side-menu ul .sub-menu li.active a,
  .nav-side-menu li .sub-menu li.active a {
    color: #d19b3d;
  }
  .nav-side-menu ul .sub-menu li,
  .nav-side-menu li .sub-menu li {
    background-color: #181c20;
    border: none;
    line-height: 28px;
    border-bottom: 1px solid #23282e;
    margin-left: 0px;
  }
  .nav-side-menu ul .sub-menu li:hover,
  .nav-side-menu li .sub-menu li:hover {
    background-color: #020203;
  }
  .nav-side-menu ul .sub-menu li:before,
  .nav-side-menu li .sub-menu li:before {
    font-family: FontAwesome;
    content: "\f105";
    display: inline-block;
    padding-left: 10px;
    padding-right: 10px;
    vertical-align: middle;
  }
  .nav-side-menu li {
    padding-left: 0px;
    border-left: 3px solid #2e353d;
    border-bottom: 1px solid #23282e;
  }
  .nav-side-menu li a {
    text-decoration: none;
    color: #e1ffff;
  }
  .nav-side-menu li a i {
    padding-left: 10px;
    width: 20px;
    padding-right: 20px;
  }
  .nav-side-menu li:hover {
    border-left: 3px solid #d19b3d;
    background-color: #4f5b69;
    -webkit-transition: all 1s ease;
    -moz-transition: all 1s ease;
    -o-transition: all 1s ease;
    -ms-transition: all 1s ease;
    transition: all 1s ease;
  }
  .collapsed{
    .arrow:before{
    font-family: FontAwesome;
    content: "\f053";
    display: inline-block;
    padding-left:10px;
    padding-right: 10px;
    vertical-align: middle;
    float:right;
  }
}




  @media (max-width: 767px) {
    .nav-side-menu {
      position: relative;
      width: 100%;
      margin-bottom: 10px;
  }
    .nav-side-menu .toggle-btn {
      display: block;
      cursor: pointer;
      position: absolute;
      right: 10px;
      top: 10px;
      z-index: 10 !important;
      padding: 3px;
      background-color: #ffffff;
      color: #000;
      width: 50px;
      text-align: center;
  }
    .brand {
      text-align: left !important;
      font-size: 22px;
      padding-left: 20px;
      line-height: 50px !important;
  }
}




  @media (min-width: 768px) {

    /*Allow main to be next to Nav*/
    .main{
      position: absolute;
      width: calc(100% - 100px); /*keeps 100% minus nav size*/
      margin-right: 100px;
      float: left;
    } 

    /*lets nav bar to be showed on mouseover*/
    nav.sidebar:hover + .main{
      margin-right: 22%;
    }

    /*Center Brand*/
    nav.sidebar.navbar.sidebar>.container .navbar-brand, .navbar>.container-fluid .navbar-brand {
      margin-right: 0px;
    }
    /*Center Brand*/
    nav.sidebar .navbar-brand, nav.sidebar .navbar-header{
      text-align: center;
      width: 100%;
      margin-right: 0px;
    }

    /*Center Icons*/
    nav.sidebar a{
      padding-right: 13px;
    }

    /*adds border top to first nav box */
    nav.sidebar .navbar-nav > li:first-child{
      border-top: 1px #e5e5e5 solid;
    }

    /*adds border to bottom nav boxes*/
    nav.sidebar .navbar-nav > li{
      border-bottom: 1px #e5e5e5 solid;
    }

    /* Colors/style dropdown box*/
    nav.sidebar .navbar-nav .open .dropdown-menu {
      position: static;
      float: none;
      width: auto;
      margin-top: 0;
      background-color: transparent;
      border: 0;
      -webkit-box-shadow: none;
      box-shadow: none;
    }

    /*allows nav box to use 100% width*/
    nav.sidebar .navbar-collapse, nav.sidebar .container-fluid{
      padding: 0 0px 0 0px;
    }

    /*colors dropdown box text */
    .navbar-inverse .navbar-nav .open .dropdown-menu>li>a {
      color: #777;
    }

    /*gives sidebar width/height*/
    nav.sidebar{
      width: 250px;
      height: 100%;
      margin-right: -170px;
      float: right;
      z-index: 8000;
      margin-bottom: 0px;
    }

    /*give sidebar 100% width;*/
    nav.sidebar li {
      width: 100%;
    }

    /* Move nav to full on mouse over*/
    nav.sidebar:hover{
      margin-right: 0px;
    }
    /*for hiden things when navbar hidden*/
    .forAnimate{
      opacity: 0;
    }


    .nav-side-menu {
    position: relative;
    width: 100%;
    margin-bottom: 10px;
    }
    .nav-side-menu .toggle-btn {
      display: block;
      cursor: pointer;
      position: absolute;
      right: 10px;
      top: 10px;
      z-index: 10 !important;
      padding: 3px;
      background-color: #ffffff;
      color: #000;
      width: 40px;
      text-align: center;
    }
    .brand {
      text-align: left !important;
      font-size: 22px;
      padding-left: 20px;
      line-height: 50px !important;
    }
  }

  @media (min-width: 767px) {
    .nav-side-menu .menu-list .menu-content {
      display: block;
    }
  }


  /* .....NavBar: Fully showing nav bar..... */

  @media (min-width: 1330px) {
    /*Allow main to be next to Nav*/
    .main{
      width: calc(100% - 250px); /*keeps 100% minus nav size*/
      margin-right: 250px;
    }

    /*Show all nav*/
    nav.sidebar{
      margin-right: 0px;
      float: right;
    }
    /*Show hidden items on nav*/
    nav.sidebar .forAnimate{
      opacity: 1;
    }
  }

nav.sidebar .navbar-nav .open .dropdown-menu>li>a:hover, nav.sidebar .navbar-nav .open .dropdown-menu>li>a:focus {
  color: #CCC;
  background-color: transparent;
}

nav:hover .forAnimate{
  opacity: 1;
}
section{
  padding-left: 15px;
} 

.nav-side-menu .menu-list .menu-content {
  display: block;
}

</style>

<script type="text/javascript">
  function press(e){
  if(e.keyCode == 13){ //javascript에서는 13이 enter키를 의미함 
  window.formname.submit(); //formname에 사용자가 지정한 form의 name입력 
  } 
} 
  function htmlbodyHeightUpdate(){
    var height3 = $( window ).height()
    var height1 = $('.nav').height()+50
    height2 = $('.main').height()
    if(height2 > height3){
      $('html').height(Math.max(height1,height3,height2)+10);
      $('body').height(Math.max(height1,height3,height2)+10);
    }
    else
    {
      $('html').height(Math.max(height1,height3,height2));
      $('body').height(Math.max(height1,height3,height2));
    }
    
  }
  $(document).ready(function () {
    htmlbodyHeightUpdate()
    $( window ).resize(function() {
      htmlbodyHeightUpdate()
    });
    $( window ).scroll(function() {
      height2 = $('.main').height()
        htmlbodyHeightUpdate()
    });
  });

</script>

app/views/projects/show.html.erb
<div class="project-inner-hc">
  <h2 style="font-family: 'Jua', sans-serif;">TOEIC</h2>
</div>

<!-- project navs bar content-->
<ul class="nav nav-pills mb-3 project-tabs-section-hc" id="pills-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">내 일정</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">성취도</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-members-tab" data-toggle="pill" href="#pills-members" role="tab" aria-controls="pills-members" aria-selected="false">멤버</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-file-tab" data-toggle="pill" href="#pills-file" role="tab" aria-controls="pills-file" aria-selected="false">파일 보내기</a>
  </li>
</ul>

<!-- project inner content -->
<div class="project-tabs-inner-hc">

  <div class="tab-content" id="pills-tabContent">
    <!-- project inner left and right padding -->

    <div class="tab-pane fade in active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="project-list">
        <div class="card project-card-hc">
          <div class="card-body">
            <h4 class="card-title">TO DO</h4>
            
            <div class="form-inputs">
              <input type="text" class="form-control plan-box-hc" placeholder="Your Plan">
            </div>
            
          </div>
          
          <div class="card-footer">
            
            <a href="#" class="card-link">
              <div class="add-description-hc">
              <span class="glyphicon glyphicon-plus" aria-hidden="true" style="display:inline-block"></span>
              <p>추가하기</p>
              </div>
            </a>
            
          </div>
        </div>

        <div class="card project-card-hc">
          <div class="card-body">
            <h5 class="card-title">Doing</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>

        <div class="card project-card-hc">
          <div class="card-body">
            <h5 class="card-title">Did</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>

        <a href="#">
          <div class="card add-plan-button-hc">
            <div class="card-body">
              <div class="add-button-body-hc">
                <span class="glyphicon glyphicon-plus" aria-hidden="true" style="display:inline-block"></span>
                <p>Add Plan</p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <!-- 성취도 section -->
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>


    <!-- 멤버 보기 section -->
    <div class="tab-pane fade " id="pills-members" role="tabpanel" aria-labelledby="pills-members-tab">
      <div class="member-list-hc">
        <div class="member-nav-hc">
          <ul class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <li><a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">전체 멤버</a></li>
            <li><a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">초대중인 멤버</a></li>
            <li><a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">삭제된 멤버</a></li>
          </ul>
        </div>
          
        <hr>
        <div class="tab-content" id="v-pills-tabContent">
          <div class="tab-pane fade in active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <div class="all-friend-hc">
              <ul>
                <li>직책</li>
                <li>홍길동</li>
              </ul>
            </div>
          </div>
          <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">...</div>
          <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
        </div>
      </div>
    </div>

    <!-- 파일 보내기 section -->
    <div class="tab-pane fade" id="pills-file" role="tabpanel" aria-labelledby="pills-file-tab">

    </div>
  </div>
</div>


임시
초대하기<br>
<%= form_tag(invite_project_path(params[:id])) do%>
  이메일 입력 : <%=text_field_tag 'email'%>
  <%=submit_tag '제출'%>
<%end%>