config/routes.rb
Rails.application.routes.draw do

  #projects 경로
  resources :projects, :except => [:show]
  get 'projects/show/:id' => 'projects#show', as: 'show_project'
  post 'projects/invite/:id' =>'projects#invite', as: 'invite_project'
  post 'projects/exit/:id' => 'projects#exit'
  get 'projects/join/:project_id&:key&:user_id' => 'projects#join', as: 'join_project' 
  get 'projects/myproject'
  post 'projects/create'
  
  #posts 경로
  resources :posts do
    post "/like", to: "likes#like_toggle"

    #댓글기능 라우팅
    #post에 속한 라우팅 기능으므로 여기에 적어준다
    resources :comments, only: [:create, :destroy]
  end

  
  
  #루트 경로
  root :to => "home#index"
  get 'home/profile', to: 'home#profile', :as => :profile

  #devise 경로
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'},
    path: 'users',
    path_name: {sign_in: 'login', sign_out: 'logout'}




  #register 경로
  get 'register/info', to: 'register#info', as: 'register_info'

  match '/profile/:id/finish_signup' => 'register#info', via: [:get, :patch], :as => :finish_signup

end

app/models/post.rb
class Post < ApplicationRecord
	resourcify
	include Authority::Abilities
	
	belongs_to :user

	has_many :likes
	has_many :comments
	# user.rb를 참조하자
	has_many :liked_users, through: :likes, source: :user

	mount_uploader :image, PostImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  ##devise gem 문서참조 로그인이 아닐시 해당 페이지 참조 불가 index는 제외하라
  before_action :authenticate_user!, execept: [:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize_action_for @post
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to '/posts', notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    authorize_action_for @post
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(user_id: @post.user_id, content: params[:post][:content], image: params[:post][:image])
        # 내가 수정한 내용
        logger.debug format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        logger.debug format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize_action_for @post
    @post = Post.find(params[:id])

    @post.destroy
    respond_to do |format|
      format.html { redirect_to '/posts', notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="card col s12 new-post-hc">
  <div class="card-content" style="padding: 5em;">
    <div class="card-title">
      <p style="font-size: 20px; ">새 게시물</p>
    </div><br />

    <%= simple_form_for @post, :html => { :multipart => true} do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :content, placeholder: "이야기를 적어주세요.."%>
      </div>

      <div class="field">
        <%= f.label "Image" %>
        <%= f.file_field :image %>
      </div><br>

      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-success"%>
      </div><br>

    <% end %>

    </div>
</div>

app/views/posts/_post.html.erb
<div class="card post">
  <div class="card-content">
    <%= image_tag('basic_img.png')%>
    <span class="card-title post-name-hc" style="display: inline; margin-right: 5px;"><%= post.user.name %></span>
    <span><%= post.created_at.strftime('%Y년 %m월 %d일 %H시 %M분') %></span>
    <div class="content">
      <hr>
      <p class="pre-line"><%= simple_format post.content %></p>
      <br>
      </div>
    <div class="card-image">
      <% if post.image.url %>
        <img src="<%= post.image.url %>" style="width: 380px; height: auto">
      <% end %>
    </div>

    <div class="card-action">
      <%= post.likes.size %>명이 좋아합니다<br><br>
      <% if current_user.is_like?(post) %>
        <%= link_to "좋아요 취소", post_like_path(post), method: "post" %>
      <% else %>
        <%= link_to "좋아요", post_like_path(post), method: "post" %>
      <% end %>


      <!-- 유저값을 확인하여 게시판을 쓴 유저이거나 관리자 계정이면  수정, 삭제버튼 확인 가능-->

      <% if user_signed_in? %>
        <%= link_to "삭제", post_path(post), method: :delete, class: "right", data: { confirm: 'Are you sure?' } if post.deletable_by? current_user %>
        <%= link_to "수정", edit_post_path(post), class: "right" if post.updatable_by? current_user %>
      <% end %>
      

      <%= form_tag post_comments_path(post) do %>
        <div class="input-field">
          <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해주세요.", required: true %>
        </div>
        <div class="input-field">
          <%= button_tag "댓글 달기", class: 'btn-primary btn', style: "background-color: #04B486;"%>
        </div>
      <% end %>
      <hr>
      <% if post.comments.present?%>
        <ul class="">
          <% post.comments.reverse.each do |c| %>
            <li class="collection-item">
              <span class="title" style="font-weight: bold; color: #5882FA;"><%= c.user.name%></span>
              <span class="right"><%= c.created_at.strftime('%Y년 %m월 %d일 %H시 %M분') %></span>
              <p style="font-size: 21px; font-family: 'Nanum Pen Script', cursive;"><%= c.content %></p>
              <% if c.user.id == current_user.id %>
                <div style="display: inline; float: right">
                  <%= link_to "삭제", post_comment_path(post, c), method: "delete" %>
                </div><br>
                <hr>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div style="width: 70%">
	<div class="card col s12">
	  <div class="card-content" style="padding: 5em;">
	    <div class="card-title">
	      <h3>Editing Post</h3>
	    </div><br />

	    <%= simple_form_for @post, :html => { :multipart => true} do |f| %>
	      <%= f.error_notification %>
	      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

	      <div class="form-inputs">
	        <%= f.input :content, placeholder: "이야기를 적어주세요.."%>
	      </div>

	      <div class="field">
	        <%= f.label "Image" %>
	        <%= f.file_field :image %>
	      </div><br>

	      <div class="form-actions">
	        <%= f.button :submit, class: "btn btn-success" %>
	      </div><br>

	    <% end %>

	  </div>
	</div>
	<%= link_to posts_path do %>
		<button>뒤로가기</button>
	<% end %>
</div>

app/views/posts/index.html.erb
<div class="card-profil-hc">
  <div class="card" style="width: 20em; display: inline-block;">
    <div class="card-img-top my-profil-hc">
      <% unless current_user.avatar.url.nil? %>
      <div class="card-image">
        <img src="<%= current_user.avatar.url %>"  style="width: 18em; height: auto; margin-right: 1em; margin-left: 1em;"/>
      </div>
      <% end %>
      <br>
      <div class="card-body">
        <span><%= current_user.name %>님의 프로필</span>
        <!-- New Post 버튼-->
        <br>
        <div class="btn-homeAndproject-hc">
          <%= link_to new_post_path do %>
            <button class="btn btn-success btn-hc-1">새 글쓰기</button>
          <% end %>

          <%= link_to root_path do %>
            <button class="btn btn-warning btn-hc-1">홈으로</button>
          <% end %>

          <%= link_to projects_path do %>
            <button class="btn btn-primary btn-hc-1">내 프로젝트</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <p id="notice"><%= notice %></p>
</div>


<div class="col s12 m8" style="width: 70%; margin-left: 25%; display: inline-block;">
  <!-- _post.html.erb에 partial -->
  <% @posts.reverse.each do |post| %>
    <%= render partial: "post", locals: { post: post } %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to '뒤로가기', posts_path, class: "back-btn-hc" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Image:</string>
	<% if @post.image.url %>
    <img src="<%= post.image.url %>" style="width: 380px; height: auto">
  <% end %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>